#!/bin/sh

. /etc/rc.subr

name=sftp_watchd
rcvar=sftp_watchd_enable

load_rc_config $name
: ${sftp_watchd_enable:=yes}

pidfile="/var/run/${name}.pid"

command="/usr/sbin/${name}" 

start_sftp_watch() {
	unlink /dev/log
	ln -s /home/sftp/dev/log /dev/log
	/usr/sbin/daemon -f -p ${pidfile} ${command}
}
start_cmd="start_sftp_watch" 

stop_sftp_watch() {
	if [ -e $pidfile ]; then
		pid=`cat $pidfile`
		kill $pid
	fi
}
stop_cmd="stop_sftp_watch"

start_precmd="echo 'Starting sftp_watchd.'" 
stop_postcmd="echo Kill: `if [ -e $pidfile ]; then cat $pidfile; fi`"

run_rc_command "$1"

